### ISSUE TITLE
Symbols?

### ISSUE THREAD

**Issue by nateabele** [18alantom/strawberry#10]
What do you think about using symbols in place of `__sb_prefix` & `__sb_dependencies`?

It would avoid polluting the property space of `reactive()` objects, and allow you to gate access to those values a bit more cleanly.

I can write up a PR if you like.

**Comment by 18alantom** [comment]
I hadn't considered it. No reason to not use it. Even if considering compatibility with the old browsers, `Proxy` breaks it.

> I can write up a PR if you like.

I'd appreciate that!
