### ISSUE TITLE
keep min files in git ?

### ISSUE THREAD

**Issue by gedw99** [18alantom/strawberry#12]
here is what i had to do to get the web site demo running:

from the web site: https://strawberry.quest/ OR https://github.com/18alantom/strawberry/tree/gh-pages :

- add script for sb-min.js to website/

- add script for highlight.min.js to to website/

--

I know i could build them locally, but i just wanted to play with the code.

SO might be easiest to include them in the website folder for ease of getting going ...

**Comment by gedw99** [comment]
also the highlight script is not mentioned in https://github.com/18alantom/strawberry/tree/main/docs#strawberry-starter

i needed it to get going..

**Comment by 18alantom** [comment]
> also the highlight script is not mentioned in https://github.com/18alantom/strawberry/tree/main/docs#strawberry-starter

This is needed only for syntax highlighting on the website, else it shouldn't be required.

---

I `.gitignore`'d the minified files cause they're used just for the website.

Will add a note in the README on getting the website working, something like this:

```bash
# clone gh-pages branch having website dependencies
git clone -b gh-pages https://github.com/18alantom/strawberry

# change directory
cd strawberry

# serve the files in the folder on 127.0.0.1:8080
python -m http.server 8080 --bind 127.0.0.1
```

**Comment by 18alantom** [comment]
Closing cause added details to the README in https://github.com/18alantom/strawberry/commit/c879bc41f02b14c4fb97a25e9124a25c19061ba2

**Comment by gedw99** [comment]
Sweet
