### ISSUE TITLE
Is there a sb-show attribute?

### ISSUE THREAD

**Issue by cipriano200** [18alantom/strawberry#23]
If there is no sb-show, is any other solution to show and hide?

**Comment by 18alantom** [comment]
@cipriano200 there's `sb-if` and `sb-ifnot` for conditional rendering. Do these suffice? ([reference](https://github.com/18alantom/strawberry/blob/main/docs/reactivity/conditionals.md))


_Note: these will be out in 0.0.2-alpha.0_

**Comment by cipriano200** [comment]
Yes they work, but sb-show would be better because can replace sb-if and sb-ifnot into 1 attribute

**Comment by 18alantom** [comment]
You'd still need two, `sb-show`, `sb-hide` which act on the truthy-ness of the value. This is cause the attribute values are just keys and not values interpreted as code (such as in Vue.js).

Either way, if you want to use a `show` attribute, you can add it in by registering a one line directive.


```html
<div sb-show="shouldShow">
  <!-- contents -->
</div>

<script>
// define a custom show directive
sb.directive('show', ({ el, value }) => (el.style.display = value ? '' : 'none'));

// toggle hidden state
data.shouldShow = false; // This will set display to 'none'
</script>
```

[Directives Documentation](https://github.com/18alantom/strawberry/blob/main/docs/reactivity/directives.md)
