### ISSUE TITLE
Directive function is not avaiable/found when loaded from cdn

### ISSUE THREAD

**Issue by alsanan** [18alantom/strawberry#29]
I'm not sure if that is from a new version or if it's needed a compilation from typescript before available.

**Comment by 18alantom** [comment]
Yup, apologies it's a bit disorganized. The docs pertain to the next version, will close this when I release that, should be out in a day or so.

**Comment by 18alantom** [comment]
New version has been released `sb.directive` should now be available:

```html
<script src="https://unpkg.com/sberry@0.0.3-alpha.0/dist/sb.min.js"></script>
```
