### ISSUE TITLE
Finally

### ISSUE THREAD

**Issue by gedw99** [18alantom/strawberry#3]
Cleanest thing I have seen in years for web frontend.. 

Is there a roadmap ? Would love to contribute

**Comment by 18alantom** [comment]
Thank you, that means a lot!

There's no concrete roadmap as of now. Mostly experimenting to build up to a base set of features that feel clean and intuitive. As for a rough roadmap, the [final ~20% of the source code file](https://github.com/18alantom/strawberry/blob/889cba7ac5a0b4dbede0c807dbcceea42dc5fe69/index.ts#L665) consists of scattered notes and a bunch things that I want to do next.

(I know it's not the best place to keep my disorganized notes and plans; I'm planning on moving these to documentation and elsewhere after a bit)

**Comment by HelloLudger** [comment]
I also want to say: Thank you! 
This is something I had in my mind, but would not be capable to develop by myself.

Probably perfect for small cheaply-hosted projects, combined with something like https://github.com/picocss or https://github.com/emareg/classlesscss .

**Comment by 18alantom** [comment]
I have added something of a roadmap: [strawberry/blob/main/ROADMAP.md](https://github.com/18alantom/strawberry/blob/main/ROADMAP.md)

**Comment by gedw99** [comment]
Will close now as no actioned needed
